### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by IgorGanapolsky** [couchand/fake-api-server#8] opened 2017-03-08 20:48 UTC
Hi,
I am following your instructions on https://www.npmjs.com/package/fake-api-server.  I am running **curl localhost:3000/api/books**, and getting this error:
> Not Found

Do you know what could be wrong?

**Comment by couchand** [comment] 2017-03-09 00:01
I'm sorry @IgorGanapolsky, you're gonna have to provide some more details to get any useful feedback.  What steps specifically have you taken so far?  You linked to the README, are you replicating that exactly?  Have you started a node server?  Was it with the exact script listed in the README?  What platform are you on?  How do you usually connect to node servers running locally?  What debugging did you attempt before filing an issue?

Without more details on what exactly you're doing and what steps you've already taken to try to diagnose and fix the issue, you're not really making it easy for anyone to help.

**Comment by IgorGanapolsky** [comment] 2017-03-09 14:12
@couchand Thank you for trying to help me.  To answer your questions:

1. **What steps specifically have you taken so far?** 
I followed the steps in the Quickstart section
2. **You linked to the README, are you replicating that exactly?** 
Exactly what it says
3. **Have you started a node server?**
Node server gets started as the README says: `node server.js &`
4. **Was it with the exact script listed in the README?**
Yes
5. **What platform are you on?** 
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
6. **How do you usually connect to node servers running locally?** 
That is irrelevant, as I am not even able to start your script
7. **What debugging did you attempt before filing an issue?**
JavaScript doesn't have a concept of debugging for Node.js

**Comment by couchand** [comment] 2017-03-12 22:11
When you say "I am not even able to start your script", what exactly do you mean? The initial bug report mentioned that your trouble was on a cURL command, which you should only try if the server's already been started.  Otherwise, of course it won't work, because there wouldn't be anything for cURL to connect to.

And regarding your last point, I don't mean debugging in the sense of connecting a debugger (though you may be interested to learn that it is indeed possible to connect a debugger to Node.js), but rather in the more general sense: what steps have you tried already in your effort to diagnose and fix the problem?

**Comment by IgorGanapolsky** [comment] 2017-03-13 13:40
@couchand I apologize for the discrepancy.  I have corrected my statement above.  And when I issue the following command:
`curl localhost:3000/api/books`

I get this output:
> Not Found

What is the best way to troubleshoot this?

**Comment by krcourville** [comment] 2017-06-19 14:15
I believe I ran into the same problem running on Windows 10, Node v6.10.2.

My resource was defined like this:

`const games = new fake.Resource("Game");`

This resulted in a 404 response.

After changing to this, it worked:

`const games = new fake.Resource("game");`

**Comment by couchand** [comment] 2017-06-22 04:19
@krcourville That doesn't sound like the same issue as the OP, since the example code is all lowercase.

@IgorGanapolsky I'm sorry, but I can't tell from your comments what the issue is that you're running into here.

As I haven't seen any code samples or other examples of how to reproduce this issue, I'm closing it.  Feel free to add more details here or open a new issue if you have specific examples of ways in which this library is not working as intended.

**Comment by couchand** [comment] 2017-06-22 04:28
@krcourville clearly I'm wrong, the README uses `"Book"` to register the resource and `/api/book` to retrieve it.  My mistake.  We should definitely fix that.

**Closed** 2017-06-22 04:32 UTC
Labels: bug
